In [1]:
import duckdb
import pandas as pd
import polars as pl

import os
os.chdir('../')

In [2]:
df = pd.read_csv('Data/housing.csv')

In [3]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [4]:
result = duckdb.query("SELECT DISTINCT ocean_proximity FROM df").to_df()
print(result)

  ocean_proximity
0          INLAND
1      NEAR OCEAN
2       <1H OCEAN
3        NEAR BAY
4          ISLAND

In [5]:
result = duckdb.query("SELECT * FROM df order by total_bedrooms DESC").to_df()
print(result)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -121.79     36.64                11.0      32627.0          6445.0
1        -121.44     38.43                 3.0      39320.0          6210.0
2        -117.74     33.89                 4.0      37937.0          5471.0
3        -118.44     33.98                21.0      18132.0          5419.0
4        -117.78     34.03                 8.0      32054.0          5290.0
...          ...       ...                 ...          ...             ...
20635    -119.19     34.20                18.0       3620.0             NaN
20636    -119.18     34.19                19.0       2393.0             NaN
20637    -118.88     34.17                15.0       4260.0             NaN
20638    -118.75     34.29                17.0       5512.0             NaN
20639    -118.72     34.28                17.0       3051.0             NaN

       population  households  median_income  median_house_value  \
0         28566.0      6082.0         2.3087            118800.0
1         16305.0      5358.0         4.9516            153700.0
2         16122.0      5189.0         7.4947            366300.0
3          7431.0      4930.0         5.3359            500001.0
4         15507.0      5050.0         6.0191            253900.0
...           ...         ...            ...                 ...
20635      3171.0       779.0         3.3409            220500.0
20636      1938.0       762.0         1.6953            167400.0
20637      1701.0       669.0         5.1033            410700.0
20638      2734.0       814.0         6.6073            258100.0
20639      1705.0       495.0         5.7376            218600.0

      ocean_proximity
0           <1H OCEAN
1              INLAND
2           <1H OCEAN
3           <1H OCEAN
4           <1H OCEAN
...               ...
20635      NEAR OCEAN
20636      NEAR OCEAN
20637       <1H OCEAN
20638       <1H OCEAN
20639       <1H OCEAN

[20640 rows x 10 columns]

Return as polars dataframe. Polars dataframes acts as Pandas, but is mutch faster

In [6]:
pl_result = duckdb.query("SELECT * FROM df order by total_bedrooms DESC").pl()
print(pl_result)

shape: (20_640, 10)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ longitude ┆ latitude ┆ housing_m ┆ total_roo ┆ … ┆ household ┆ median_in ┆ median_ho ┆ ocean_pro │
│ ---       ┆ ---      ┆ edian_age ┆ ms        ┆   ┆ s         ┆ come      ┆ use_value ┆ ximity    │
│ f64       ┆ f64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆          ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ str       │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ -121.79   ┆ 36.64    ┆ 11.0      ┆ 32627.0   ┆ … ┆ 6082.0    ┆ 2.3087    ┆ 118800.0  ┆ <1H OCEAN │
│ -121.44   ┆ 38.43    ┆ 3.0       ┆ 39320.0   ┆ … ┆ 5358.0    ┆ 4.9516    ┆ 153700.0  ┆ INLAND    │
│ -117.74   ┆ 33.89    ┆ 4.0       ┆ 37937.0   ┆ … ┆ 5189.0    ┆ 7.4947    ┆ 366300.0  ┆ <1H OCEAN │
│ -118.44   ┆ 33.98    ┆ 21.0      ┆ 18132.0   ┆ … ┆ 4930.0    ┆ 5.3359    ┆ 500001.0  ┆ <1H OCEAN │
│ -117.78   ┆ 34.03    ┆ 8.0       ┆ 32054.0   ┆ … ┆ 5050.0    ┆ 6.0191    ┆ 253900.0  ┆ <1H OCEAN │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ -119.19   ┆ 34.2     ┆ 18.0      ┆ 3620.0    ┆ … ┆ 779.0     ┆ 3.3409    ┆ 220500.0  ┆ NEAR      │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OCEAN     │
│ -119.18   ┆ 34.19    ┆ 19.0      ┆ 2393.0    ┆ … ┆ 762.0     ┆ 1.6953    ┆ 167400.0  ┆ NEAR      │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ OCEAN     │
│ -118.88   ┆ 34.17    ┆ 15.0      ┆ 4260.0    ┆ … ┆ 669.0     ┆ 5.1033    ┆ 410700.0  ┆ <1H OCEAN │
│ -118.75   ┆ 34.29    ┆ 17.0      ┆ 5512.0    ┆ … ┆ 814.0     ┆ 6.6073    ┆ 258100.0  ┆ <1H OCEAN │
│ -118.72   ┆ 34.28    ┆ 17.0      ┆ 3051.0    ┆ … ┆ 495.0     ┆ 5.7376    ┆ 218600.0  ┆ <1H OCEAN │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [8]:
pl_result.head()

shape: (5, 10)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ longitude ┆ latitude ┆ housing_m ┆ total_roo ┆ … ┆ household ┆ median_in ┆ median_ho ┆ ocean_pro │
│ ---       ┆ ---      ┆ edian_age ┆ ms        ┆   ┆ s         ┆ come      ┆ use_value ┆ ximity    │
│ f64       ┆ f64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆          ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ str       │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ -121.79   ┆ 36.64    ┆ 11.0      ┆ 32627.0   ┆ … ┆ 6082.0    ┆ 2.3087    ┆ 118800.0  ┆ <1H OCEAN │
│ -121.44   ┆ 38.43    ┆ 3.0       ┆ 39320.0   ┆ … ┆ 5358.0    ┆ 4.9516    ┆ 153700.0  ┆ INLAND    │
│ -117.74   ┆ 33.89    ┆ 4.0       ┆ 37937.0   ┆ … ┆ 5189.0    ┆ 7.4947    ┆ 366300.0  ┆ <1H OCEAN │
│ -118.44   ┆ 33.98    ┆ 21.0      ┆ 18132.0   ┆ … ┆ 4930.0    ┆ 5.3359    ┆ 500001.0  ┆ <1H OCEAN │
│ -117.78   ┆ 34.03    ┆ 8.0       ┆ 32054.0   ┆ … ┆ 5050.0    ┆ 6.0191    ┆ 253900.0  ┆ <1H OCEAN │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘